### ISSUE TITLE
uninitialized constant TOML

### ISSUE THREAD

**Issue by bcg62** [nathwill/chef-crio#5]
```
   NameError
   ---------
   uninitialized constant TOML

   Cookbook Trace: (most recent call first)
   ----------------------------------------
     /tmp/packer-chef-solo/cookbooks-0/crio/libraries/mixins.rb:30:in `to_toml'
     /tmp/packer-chef-solo/cookbooks-0/crio/recipes/configure.rb:23:in `block in from_file'
     /tmp/packer-chef-solo/cookbooks-0/crio/recipes/configure.rb:22:in `from_file'
     /tmp/packer-chef-solo/cookbooks-0/crio/recipes/default.rb:9:in `block in from_file'
     /tmp/packer-chef-solo/cookbooks-0/crio/recipes/default.rb:8:in `each'
     /tmp/packer-chef-solo/cookbooks-0/crio/recipes/default.rb:8:in `from_file'

   Relevant File Content:
   ----------------------
   /tmp/packer-chef-solo/cookbooks-0/crio/libraries/mixins.rb:

    23:        end
    24:      end
    25:    end
    26:  end
    27:
    28:  class Hash
    29:    def to_toml
    30>>     require 'toml'
    31:      TOML::Generator.new(self).body
    32:    end
    33:  end
    34:

   System Info:
   ------------
   chef_version=18.3.0
   platform=redhat
   platform_version=8.9
   ruby=ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
   program_name=/opt/cinc/bin/cinc-solo
   executable=/opt/cinc/bin/cinc-solo
```

**Comment by bcg62** [comment]
this works up to 16.18.30, once on v17/v18 this error surfaces.
